### ISSUE TITLE
RFC-0022: Feed bucket menus need to be in footer in case of mobile view (review needed)

### ISSUE THREAD

**Issue by tenkus47** [OpenPecha/monlamai-app-web#103]
solves https://github.com/OpenPecha/monlamai-requests/issues/57

### Description
Feedback menus need to be put in the footer in mobile view, as it is very difficult to write an input.

![Image](https://github.com/OpenPecha/monlam_ai_tools/assets/42644738/0f12feab-daac-4052-92d0-35b05ac1cb75)

In the mobile view, controls should open from right to left or at the bottom for accessibility. 

### Completion Criteria
Feed bucket menus on the footer in case of mobile view when the user toggles.

### Implementation Plan
First, go through the documents for such properties on mobile view. If not then check if feedbucket CSS can be overridden.
Override to get the desired output.

### Subtasks 
- [x] do through documents
- [ ] check if feedbucket CSS can be customised.
- [ ] Override the CSS to make control at the bottom.
