### ISSUE TITLE
RFC-0025 Not able to upload image in OCR using camera

### ISSUE THREAD

**Issue by tentamdin** [OpenPecha/monlamai-app-web#106]
### Description
As of now we have only file upload options available in our Monlam Web app OCR feature. Files cannot be uploaded directly from the camera of the mobile.

### Completion Criteria
Where users can upload images through mobile cameras and webcam on the laptop

### Implementation Plan
check the user's device before opening the camera. Based on the device, display the user camera to capture images.

### Sub Task

- [x] Check users device
- [x] display camera based on the device
- [x] capture the image and send to OCR API

[Reference](https://github.com/orgs/OpenPecha/projects/58/views/3?pane=issue&itemId=58338516)
