### ISSUE TITLE
RFC-0026: Add and edit missing UI in mock UI design by Tamding (UI/UX)

### ISSUE THREAD

**Issue by tentamdin** [OpenPecha/monlamai-app-web#107]
### Description
We have a new mock UI design by Tamding but some UI components are missing so we have to add and edit UI components to it.

### Completion Criteria
A new mock UI with missing UI components added.

### Implementation Plan
Go through the new mock UI and compare it with a production Monlam AI webpage. List out the missing components. Create or add those missing UI components.

### Sub-tacks

- [x] Compare and list out missing UI components
Missing UI components
MT Page:
- [x]  Input Option (Text (Documents) buttons.
- [x]  Source lang. and target lang. need to be a select option instead of plain.
- [x]  Edit button (Icon) and edit page UI

TTS Page:
- [x] Input Option (Text (Documents) btns.
- [x] Playback rate changing UI

STT Page:
- [x] Input Option (Text / File) buttons.
- [x]  Audio recording duration limit below card (helper text) 
- [x]  Edit button (Icon) and edit page UI

OCR Page:
- [x] Input Option (Image / Zipe file/ PDF file) buttons.
- [x] File upload UI (Image) and button to capture the image. 
- [x] Edit button (Icon) and edit page UI

SHARE Page:
- [x] share page for mt
- [x] share page for tts
- [x] share page for stt
- [x] share page for ocr
- [x] translated version of each share page

- [ ] The document/ File input page is missing for all models.

- [x] create components or add existing components.
