### ISSUE TITLE
check UI for specified bug

### ISSUE THREAD

**Issue by tenkus47** [OpenPecha/monlamai-app-web#109]
### Description
We went throught all the model and used is as if we are the app consumer. and found out some bugs ourself.

### Completion Criteria
new mock UI should not contain the bugs that are specified below

### Implementation Plan
we are going to recheck all the bug that are specified below in the mock ui and change the ui accordingly

### Sub-tacks
 UI related:
- [x] ? in ocr overlaping text. absolute position error, maybe right bottom is ok 
- [x] share ui not loading image on OCR (New UI)
- [x] progress while uploading should be nice (UI)
- [x] share ui is not responsive to mobile. (New UI)

footer
- [x] footer background not to be highlight
- [x] footer to have only logo on mobile with copyright

STT
- [x] localise limits of audio length ( UI)

TTS
- [x] make playback rate is combined with audio level.

deepl comparison

- [x] font size change on text limit (check/test)
- [x] share of mt show footer as fixed and overlaping the data (UI)

Code related:
- [x] share ui not replace english terms in there
- [x] like dislike notification is to position well (code)
- [x] basic function needed eg. croping rotating etc for picture (code)
- [x] copy button not working on edited data (code)
- [x] login button to how in alert while choosing file upload (code)

STT
- [x] share -> pause button not changing afterplay (code)

TTS
- [x] share audioplaying not working . (code)
