### ISSUE TITLE
Change in Mock UI after consulting with Tamding(UI/UX)

### ISSUE THREAD

**Issue by tenkus47** [OpenPecha/monlamai-app-web#111]
### Description
After consulting with Tamding(UI/UX) regarding the mock UI, some changes were suggested and we have to make the new changes in the mock UI.

### Completion Criteria
A new mock UI with new changes we have discussed.

### Implementation Plan
We will create some components and variants for the changes. We will use those variants to complete the new mock UI.

### Sub Task

- [x] change or new component and variant
- [x] use variants in MT
- [x] use variants in TTS
- [x] use variants in STT
- [x] use variants in OCR
- [x] edit file/text selection UI with according to consulted  in local component
