### ISSUE TITLE
New changes in Mock UI

### ISSUE THREAD

**Issue by tentamdin** [OpenPecha/monlamai-app-web#114]
### Description
Some changes are introduced after demonstrating the mock UI to the product owner. Mainly we will take inspiration from the DeepL platform. 

### Completion Criteria
A new mock UI that reflects the updated requirements and changes.
Ensure the new UI aligns with the look and feel of the DeepL platform.
Obtain approval from the product owner on the new mock UI.

### Implementation Plan
We will create components and variants for the models by taking inspiration from the DeepL UI image below. Do the changes as per our requirement and apply to new mock UI.

![Image](https://github.com/OpenPecha/monlam_ai_tools/assets/38410384/6c698c16-c7b1-46bd-94f4-9727e6085110)

### Sub-tasks
 Header components and their variants
- [x] MT
- [x] TTS
- [x] STT
- [x] OCR

Textarea components and their variants (light version)
- [x] MT
- [x] TTS
- [x] STT
- [x] OCR

Textarea components and their variants (dark version)
- [x] MT
- [x] TTS
- [x] STT
- [x] OCR

Action Button components and their variants
- [x] MT
- [x] TTS
- [x] STT
- [x] OCR

- [x] Background colour changes for all
- [x] On edit, display only the save button
- [x] check components and variants on Mock UI
- [x] Prototype all models and components
