### ISSUE TITLE
suggestion from geshe monlam la

### ISSUE THREAD

**Issue by tenkus47** [OpenPecha/monlamai-app-web#142]
## Introduction

this are some minor ui suggestion from geshe monlam la
## Objectives

mostly reviewed on darkmode , apply the suggestion to staging

## Completion Criteria

New UI need approval from geshe lobsang monlam 

![Image](https://github.com/OpenPecha/monlam_ai_tools/assets/42644738/27e1e5cf-4468-4fa5-8634-627289bd7b92)

regarding the ocr .

## Implementation Plan

Subtasks
 

- [x]  ocr to check in if there is tibetan in it or not
- [x] check for charactor length in ocr
- [x] mt loading color dark mode not good .
- [x] stt and mt api error 
- [x] file upload cloud image need to be yellow and button to delete need to be yellow
- [x] text under image need to be same as monlam text
- [x] monlam mitra text need to be monlam font
- [x] audio player button to be primary 500
