### ISSUE TITLE
Unit testing setup for remix

### ISSUE THREAD

**Issue by Karma-Tsering** [OpenPecha/monlamai-app-web#148]
### description
Based on the conversation with Cho Samten, our current focus will be on writing unit and integration tests for our web app. As our app is developed in Remix, I will be researching testing in Remix and bringing it to our app.

### Completion criteria
Setup the unit testing in monlam ai tool

### subtasks

- [x] setting up the unit testing for remix.
- [x] Write test case for fileSizeFormat function in utils file
- [x] Write test case for timeSince function in utils file
