### ISSUE TITLE
Detect PWA users

### ISSUE THREAD

**Issue by tenkus47** [OpenPecha/monlamai-app-web#149]
### Description

Detect if a user is using the PWA (Progressive Web App) feature of the web app.

![Image](https://github.com/OpenPecha/monlam_ai_tools/assets/42644738/81d16afc-b4e4-4b06-949a-40d8dc33f911)

### Completion Criteria

- Successfully identify if a user is accessing the web app as a PWA.
- Log or store this information to the user database or store it for analytics purposes.

### Implementation Plan

- Use the window.matchMedia API to detect if the web app is running in standalone mode.
Store this information and use it to log or display the user's access mode.
Display Detection Result:

- Show a message on the web app indicating whether the user is using the PWA feature.
Optionally, send this information to an analytics service for further analysis.

### SubTasks
- [x] Configure Service Worker for PWA
- [x] Implement PWA Detection Logic
- [x] Store the data in User table
