### ISSUE TITLE
Audio Wave and Text Autocorrect Bug

### ISSUE THREAD

**Issue by tentamdin** [OpenPecha/monlamai-app-web#150]
### Description
While testing, the audio wave UI was not displaying on Safari browsers even when audio was recorded. Also in tts and stt, while typing on the mobile the cursor is coming at the start of the textarea after autocompleting a word. we have to fix those bugs

### Completion Criteria
Audio wave UI displays properly on all browsers and fixes the cursor problem.

### Implementation Plan
Inspect the application check if the wave is generated properly and check the audio URL. If the URL is not supported make it into a compatible one and serve. 

### Sub Task

- [x] Inspect the audio URL and check the compatibility
- [x] serve a supported audio URL
- [x] fix the cursor and key enter bug
