### ISSUE TITLE
Test websocket for translation response

### ISSUE THREAD

**Issue by tenkus47** [OpenPecha/monlamai-app-web#169]
### Description

Since our web app  api credentials are visible to the end , i am planing to implement web socket to send respond to the web app.
will try with the translation.

### Completion Criteria

- instead of sending the credential to the app through loader or cookie, the respond of the translation will be sent using web sockets.

### Implementation Plan

initialize a web socket in the server.js file and connect each app user to the socket, when ever the user trigger a event in the app to translate the server will sent a respond event with the translated data.

### Subtasks

- [x] initialise socket in server.js file
- [x] connect to the socket using react socket.io client
- [x] parse the respond from the translation
