### ISSUE TITLE
test system log management using Papertrail

### ISSUE THREAD

**Issue by tenkus47** [OpenPecha/monlamai-app-web#170]
### Description

Our application and all the application deployed using render need a log management system and since render log management can 
be easily integrated with [papertrail](https://papertrailapp.com/)  and also it support saving the history log file in s3 which is one of the things we need.

### Completion Criteria

- papertrail should be able to keep track of logs that are running on our render server
- this should make the study and filtering of logs much easier

### Implementation Plan

we need to make a account using openpecha@gmail.com on paper trail and connect it to the servers running on render using log streaming feature of render.
doing so will make the server log available in papertrail dashboard.

### Subtasks

- [x] create account and start up paper trail
- [x] connect paper trail to render log streaming
- [ ] testing logs in paper trail dashboard
