### ISSUE TITLE
RFC004: Team page implementation according to Mock

### ISSUE THREAD

**Issue by kaldan007** [OpenPecha/monlamai-app-web#197]
### Description

Per the mock design, we must create the team and individual page components on the monlamai website.

### Completion Criteria
Updated website with team page route listing out all the team members and individual page for details of a team member.

### Implementation Plan
- create a team page route
- List all the members using a team component.
- team detail page with individual route

### SubTasks

- [x] Create a team page route
- [x] team page component
- [x] create bo & en team data json
- [x] individual member route with details
- [ ] Upload the team headshot to s3 and use s3 link on the team page
- [x] update team data

**Comment by kaldan007** [comment]
@tentamdin refer the mock update and make require changes

**Comment by tentamdin** [comment]
- [ ] localization in team n individual page
- [ ] Update breadcrumb
