### ISSUE TITLE
Logo Design for Monlam Translate and Monlam Chatbot

### ISSUE THREAD

**Issue by TenzDelek** [OpenPecha/monlamai-app-web#231]
### Description
To create Logo for Monlam Translate and Monlam Chatbot

### Completion Criteria
1. design align with the current branding
2. Two Svg/png image logo
### Implementation Plan
1. Create a rough design on paper to verify with the Maintainer
2. implement the design on either illustrator or figma
3. create a mock for the logo on different theme

### SubTasks

- [ ] Creating Logo idea on paper
- [ ] implement the design on either illustrator or figma
- [ ] create a mock for the logo on different theme
