### ISSUE TITLE
RFC-0024: Socket Implementation of file Progress

### ISSUE THREAD

**Issue by tenkus47** [OpenPecha/monlamai-app-web#84]
### Description

When a user upload a file in any OCR and MT model the browser need to fetch a status report to the api after 2sec of interval,
which causes unnecessary API call. we can solved it using socket IO .

### Completion Criteria

Progress should update without doing a fetch api on interval

### Implementation Plan 

Socket.IO is a library that enables low-latency, bidirectional and event-based communication between a client and a server.
using this we can update client without need of api calls.

after each chunk of data at file Conversion server, we can update the progress and send a progressUpdate message to the client ,
when the client gets the event , it can trigger an update to the browser .

### Subtasks

- [x] implementation of socket at server in MT 
- [x] implementation of socket update at client MT
- [x] implementation of socket at server in OCR 
- [x] implementation of socket update at client OCR
- [x] implementation of socket at server in TTS 
- [x] implementation of socket update at client TTS
- [x] implementation of socket at server in STT 
- [x] implementation of socket update at client STT
- [x] error handling at inference list
