### ISSUE TITLE
RFC-0013: Speech output speed setter required for TTS

### ISSUE THREAD

**Issue by tenkus47** [OpenPecha/monlamai-app-web#98]
### Description
To create a playback rate button  (speed setter) for TTS audio output

### Completion Criteria
TTS speech-out button with playback rate to adjust for users on the TTS page.

### Implementation Plan
we have access to the output audio url from the file api. we can assign the audio url to the input .
using a ref we can manipulate the playback speed and the pitch of the audio. 

![Image](https://github.com/OpenPecha/monlam_ai_tools/assets/42644738/091f1215-0a59-46d9-a145-8c5bd6948a71)

### Sub Task

- [x] make a button on UI for changing the playback rate
- [x] function to change playback rate
- [x] make playback rate sticky
